apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "menu-api.fullname" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ include "menu-api.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "menu-api.fullname" . }}
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: {{ .Values.logLevel }}
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: DATABASE_PASSWORD
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: DATABASE_HOST
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: DATABASE_NAME
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: DATABASE_PORT
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: API_USERNAME
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "menu-api.fullname" . }}
              key: API_PASSWORD
      {{- if eq .Values.global.env "dev" }}
        image: "menu-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: {{ include "menu-api.fullname" . }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-menu-api
          protocol: TCP
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/app/swagger.yaml
          initialDelaySeconds: 5
          periodSeconds: 60
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "menu-api.serviceAccountName" . }}
      {{- end }}
